version: '3.8'

services:
  mysql_db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: Daddy360!
      MYSQL_DATABASE: personal_website_db

    volumes:
      - ./data/mysql/db:/var/lib/mysql 
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql_db", "-u", "root", "--password=Daddy360!"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - my-network
    depends_on:
      - mysql_db
    command: ["./wait-for-mysql.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
